### ISSUE TITLE
Add  details page/feature

### ISSUE THREAD

**Issue by ChristopherPHolder** [ChristopherPHolder/markets#26]
## Feature overview

The details page will be accessible under the following url: 
- example.com/listing-details/?:listing-id

It will pull in the listing id from the activated route.

It will fetch the data in a route resolver using the listing id

Display product not found id resolver fails

The data will be split into to sections: 
1. Item details
2. Purchase details

### Item details
- Title
- Images (main img specified)
- General details
  - Category
  - State (location)
  - Condition: New or used
  - Brand
  - Model
  - Year
  - Feet
  - Horse power
- Moter Details
  - Number of motors
  - Motor Brand
  - Horse Power
- Description

 ### Purchase details
- year
- category
- Seller's Informaation
  - Name
  - Telephone 
  - Email

## TODOS
- [ ] Create ListingDetails type
- [ ] Add route with optional params
- [ ] Add a resolver
  - [ ] Display not found it resolver fails
