### ISSUE TITLE
Move link service out of api service 

### ISSUE THREAD

**Issue by ChristopherPHolder** [ChristopherPHolder/markets#35]
## Motivation
- Improve separation of concerns by not calling a service inside another service.
- Improve testability of services as there is no master service and value service relationship.
- Improve maintainability of feature by moving the logic to the container component.

## Current State
Currently linkService `external-resource-link` is being called inside of apiService `data-access`. 

```ts
  addPreloadLCPLinks():void {
    this.getHighlightListings().pipe(tap((listings) => {
      if (!listings) {
        return;
      }
      for (let i = 0; i < 2; i++) {
        this.linkService.addLink({
          rel: 'preload',
          as: 'image',
          href: listings["watercrafts"][i].thumbnailUrl,
          fetchpriority: 'high'
        });
      }
    })).subscribe();
  }

  private addPreloadFetchLink(): void {
    this.linkService.addLink({
      rel: 'preload',
      as: 'fetch',
      type: 'application/json',
      href: this.apiEndpoint,
      crossorigin: ''
    });
  }

```

## Desired State
The external-resource-link lib is not imported the apiService.

## TODO
- [x] Trace uses of `external-resource-link` in code base. [35#issuecomment-1412464067](https://github.com/ChristopherPHolder/markets/issues/35#issuecomment-1412464067)
- [x] Move the `addPreloadLCPLinks` logic out of `ApiService` and into the `initializeDataFactory` directly.
- [ ] Move `initializeDataFactory` from `AppModule` to the `data-access` lib as a service. 
- [ ] Move the `addPreloadFetchLink` logic out of `getHighlightListings` and into the container features or its route resolver.
- [ ] Remove `external-resource-link` from `ApiService`
- [ ] Fix apiService test

**Comment by ChristopherPHolder** [comment]
## Usage of external-resource-link

- data-access/api-service -> `addPreloadFetchLink`
  - data-access/api-service -> `addPreloadLCPLinks`
    - maritime/app.module -> `initializeDataFactory`
  - data-access/api-service/addPreloadLCPLinks -> `getHighlightListings`

Note: to make it easer to create list or illustrations I will try to write it in plan English. And try con write it as the story of the link service. 

The `LinkService` is only ever imported in one place, in the `ApiService`. 
Inside which it's called 3 time, the first is in the constructor as its being passed as a service. 
The two others are in methods which cause side affects and return void, a public method `addPreloadLCPLinks`  and a private method `addPreloadFetchLink`.

---
** Usage of `addPreloadLCPLinks`**

The public method `addPreloadLCPLinks` is only used in the app initialiser in `initializeDataFactory`.
inside it calls to `getHighlightListings` and subscribes to its return observable.

This method is used to intercept the fetch request from the preload link tags, and inject two new preload tags based on the values provided by the observable. 

**Refactoring of `addPreloadLCPLinks`**
- [ ] Move the `addPreloadLCPLinks` logic out of `ApiService` and into the `initializeDataFactory` directly.
- [ ] Move `initializeDataFactory` from `AppModule` to the `data-access` lib as a service. 

---


**Usage of `addPreloadFetchLink`**

The private method `addPreloadFetchLink` is only called once, inside `getHighlightListings`.
The public method called `getHighlightListings` which return the highlights as an observable or null as an observable. 
It is called only when running in the server, and return the observable of null after to exit the method.
If its not on the server it will fetch the data instead of adding the preload links to the DOM.

**Refactoring of `addPreloadFetchLink`**

- [ ] Move the `addPreloadFetchLink` logic out of `getHighlightListings` and into the container features or its route resolver.

This would convert `getHighlightListings` from this:
```ts
  getHighlightListings(): Observable<HighlightListingsPreviews | null> {
    if (!this.isBrowser) {
      this.addPreloadFetchLink();
      return of(null);
    }
    if (!this.highlights$) {
      this.highlights$ = this.fetchHighlights();
    }
    return  this.highlights$;
  }
```

To this:
```ts
  getHighlightListings(): Observable<HighlightListingsPreviews> {
    if (!this.highlights$) {
      this.highlights$ = this.fetchHighlights();
    }
    return  this.highlights$;
  }
```

---


Notes: 
- `getHighlightListings` probably should return null as an observable.
- `highlights$`probably should not be initialised in `getHighlightListings`
- `addPreloadFetchLink` is only necessary on the server and can probably be conditionally imported.
