### ISSUE TITLE
Add Highlights for Services Products to the landing Page

### ISSUE THREAD

**Issue by ChristopherPHolder** [ChristopherPHolder/markets#8]
**TODOS**
 - [ ] Landing page has 3 highlight sections
 - [ ] Highlight sections are divided with a line
 - [ ] Highlight sections are followed by a `more` btn

The Landing page short display the preview section: 
- Watercraft
- Products
- Services

Each section should have a different heading
- Featured Watercraft
- Featured Products
- Featured Services

Between each section there should be a separation line

eg.
---

Each section should contain `more` button under them. 

eg. 

![Screenshot 2022-11-27 at 16 45 24](https://user-images.githubusercontent.com/40126819/204144189-e39f554e-7bbe-4f40-b2ab-1ac6772ba3f6.png)

For the scope of this ticket the button is none functional ...
